//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ItemAssistant.rc
//
#define ID_SEPARATOR                    0
#define ID_DEFAULT_PANE                 0
#define VS_VERSION_INFO                 1
#define IDC_MYICON                      2
#define IDD_FORMVIEW                    101
#define IDD_PLAYERSHOP                  101
#define IDD_ITEMASSISTANT_DIALOG        102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDR_MAINFRAME                   128
#define IDR_INVENTORY_VIEW              129
#define IDR_DEBUG_VIEW                  130
#define IDD_MSG_FORM                    130
#define IDD_MSG_FORM1                   131
#define IDD_BOT_FORM                    131
#define IDS_AUNO_ITEMREF_URL            131
#define IDD_INV_FIND                    132
#define IDS_JAYDEE_ITEMREF_URL          132
#define IDR_INV_ACCEL                   133
#define IDS_AO_ITEMREF_URL              133
#define IDD_PATTERN_MATCHER             134
#define IDR_PB_ACCEL                    135
#define IDD_ITEM_INFO                   136
#define IDD_WEB                         140
#define IDR_HTML1                       141
#define IDR_HTML2                       142
#define IDR_TRAY_POPUP                  143
#define IDR_ITEM_POPUP                  144
#define IDD_DUAL_PROGRESS               145
#define IDB_INVENTORY_VIEW              146
#define IDB_AOMESSAGE_VIEW              147
#define IDB_PATTERNMATCH_VIEW           148
#define IDB_PLAYERSHOP_VIEW             149
#define IDR_ITEM_POPUP_MULTISEL         150
#define IDS_XYPHOS_ITEMREF_URL          151
#define IDD_SERVER_SELECTOR             152
#define IDR_TEMPLATE                    153
#define IDB_SUMMARY_VIEW                154
#define IDB_IDENTIFY_VIEW               155
#define IDD_RENAME_BACKPACK             156
#define IDD_RECIPES                     158
#define IDR_HTML3                       159
#define IDD_RECIPES_MANAGE              161
#define IDC_EDIT2                       1001
#define IDC_LIST1                       1002
#define IDC_EDIT1                       1003
#define IDC_EDIT3                       1004
#define IDC_BUTTON1                     1005
#define IDC_COMBO1                      1006
#define IDC_ITEMTEXT                    1007
#define IDC_CHARCOMBO                   1008
#define IDC_STATIC_TOON                 1009
#define IDC_RECIPECOMBO                 1009
#define IDC_DIMENSION_COMBO             1010
#define IDC_PIECES                      1011
#define IDC_STATIC_TOON2                1011
#define IDC_STATIC_DIMENSION            1011
#define IDC_NOVI                        1012
#define IDC_PBCOMBO                     1013
#define IDC_PARTIALS                    1014
#define IDC_COMPLETE                    1015
#define IDC_CHECK5                      1017
#define IDC_COMPLETABLE                 1018
#define IDC_READY                       1019
#define IDC_LIST2                       1021
#define IDC_SQL_EDIT                    1022
#define IDC_LISTVIEW                    1023
#define IDC_AUNO                        1024
#define IDC_AODB                        1025
#define IDC_JAYDEE                      1025
#define IDC_IE_PLACEHOLDER              1028
#define IDC_SHOW_ALL                    1029
#define IDC_PROGRESS                    1030
#define IDC_SHOW_PARTIALS               1031
#define IDC_VERSION                     1031
#define IDC_TREE1                       1032
#define IDC_DESCRIPTION1                1033
#define IDC_SHOW_PARTIALS2              1033
#define IDC_SHOW_INFERNO_CLAN           1033
#define IDC_DESCRIPTION2                1034
#define IDC_SHOW_INFERNO_OMNI           1034
#define IDC_DESCRIPTION3                1035
#define IDC_PROGRESS1                   1036
#define IDC_PROGRESS2                   1037
#define IDC_QLMIN                       1038
#define IDC_QLMAX                       1039
#define IDC_BUTTON_LABEL                1040
#define IDC_EXCLUDE_ASSEMBLED           1041
#define IDC_XYPHOS                      1045
#define IDC_NONE                        1046
#define IDC_BUTTONMANAGE                1048
#define IDC_BUTTONMANAGE2               1049
#define IDC_BUTTONREFRESH               1049
#define IDC_CHARACTERCOMBO              1050
#define IDC_BUTTON_EXPORT               1051
#define IDC_BUTTON_DELETE               1052
#define IDC_BUTTON4                     1053
#define IDC_BUTTON_EDIT                 1053
#define IDC_BUTTON_NEW                  1054
#define IDC_BUTTON_IMPORT               1055
#define ATL_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define ID_Menu                         32771
#define ID_VIEW_INVENTORY               32772
#define ID_VIEW_MESSAGES                32773
#define ID_PAUSE_TOGGLE                 32774
#define ID_RECALCULATE                  32775
#define ID_VIEW_INFOPANEL               32778
#define ID_INV_FIND                     32782
#define ID_INV_FIND_TOGGLE              32783
#define ID_INV_FIND_HIDE                32784
#define ID_PB_FILTER                    32786
#define ID_PB_FILTER_HIDE               32787
#define ID_INFO                         32789
#define ID_RECORD_STATS_TOGGLE          32790
#define ID_TRAYMENU_SHOW                32791
#define ID_TRAYMENU_                    32792
#define ID_TRAYMENU_ABOUTITEMASSISTANT  32793
#define ID_TRAY_TOGLE                   32795
#define ID_COPY_AUNO_ITEMREF            32800
#define ID_COPY_JAYDEE_ITEMREF          32801
#define ID_COPY_BB_ITEMREF              32802
#define ID_COPY_AO_ITEMREF              32803
#define ID_COPY_AUNO_ITEMREF_VBB        32811
#define ID_COPY_JAYDEE_ITEMREF_VBB      32812
#define ID_VIEW_ITEMSTATS_AUNO          32816
#define ID_VIEW_ITEMSTATS_JAYDEE        32817
#define ID_ITEMCONTEXTMENU_EXPORTTO     32820
#define ID_EXPORTTOCSV_AUNO             32821
#define ID_EXPORTTOCSV_JAYDEE           32823
#define ID_HELP_SUPPORTFORUM            32825
#define ID_HELP_CHECKFORUPDATES         32826
#define ID_COPYITEMHTMLLINK_XYPHOS      32827
#define ID_COPYITEMVBBLINK_XYPHOS       32828
#define ID_COPY_XYPHOS_ITEMREF_VBB      32829
#define ID_COPY_XYPHOS_ITEMREF          32830
#define ID_EXPORTITEMTOCSVFILE_XYPHOS   32831
#define ID_EXPORTTOCSV_XYPHOS           32832
#define ID_VIEWITEMSTATS_XYPHOS         32833
#define ID_VIEW_ITEMSTATS_XYPHOS        32834
#define ID_COPY_ITEMNAME                32836
#define ID_REFRESH                      32837
#define ID_ITEMCONTEXTMENU_DELETEITEM   32838
#define ID_DELETE                       32839
#define ID_ITEMCONTEXTMENU_DELETEITEMS  32840
#define ID_OPTIONS_MANUALPREFS          32841
#define ID_OPTIONS_AUTOMATICPREFS       32842
#define ID_OPTIONS_MINIMISETOTASKBAR    32844
#define ID_OPTIONS_SHOWCREDS            32845
#define ID_RENAME_BAG                   32851
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_PANE_CLOSE                   0xE152
#define ID_FORMAT_FONT                  0xE160
#define ID_SCROLL_UP                    0xE170
#define ID_SCROLL_DOWN                  0xE171
#define ID_SCROLL_PAGE_UP               0xE172
#define ID_SCROLL_PAGE_DOWN             0xE173
#define ID_SCROLL_TOP                   0xE174
#define ID_SCROLL_BOTTOM                0xE175
#define ID_SCROLL_LEFT                  0xE176
#define ID_SCROLL_RIGHT                 0xE177
#define ID_SCROLL_PAGE_LEFT             0xE178
#define ID_SCROLL_PAGE_RIGHT            0xE179
#define ID_SCROLL_ALL_LEFT              0xE17A
#define ID_SCROLL_ALL_RIGHT             0xE17B
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_TRAY_SHOW                    0xE802
#define ID_VIEW_REFRESH                 0xE803
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
